### ISSUE TITLE
Remove default "Uncategorized" category when other categories are selected

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/cms.theworld.org#203]
Figure out a hook/action/filter to use to remove the default category when:
- Number of selected categories is greater than 1
- Default "Uncategorized" category is in selected categories.

**Comment by brandonhundt** [comment]
@rpeterman-gp I'm going to add this one to the Four Kitchens queue

**Comment by gtenaschuk** [comment]
@rpeterman-gp 
Is this for existing posts or for new posts?

Asking this because a default category is required for wordpress posts, but only when you create a post without selecting another category, so:
-  when you create a post without selecting a category, the default category will be associated to it. 
-  when you create a post with a category selected, the default one won't be associated to the post.

**Comment by brandonhundt** [comment]
Wontfix!
